### ISSUE TITLE
Error when running `kubectl describe namespace <namespace>`

### ISSUE THREAD

**Issue by jclynny** [dty1er/kubecolor#36] opened 2020-12-02 22:59 UTC
I am on Mac OSX v. 10.15.7 (Catalina) and Kubecolor 0.0.7 installed from brew, and I'm using zsh in iTerm2.  I get the following errors when trying to describe namespace resources in K8s:

Resource Quotas
  Name:panic: runtime error: index out of range [0] with length 0

goroutine 18 [running]:
github.com/dty1er/kubecolor/printer.(*DescribePrinter).Print(0xc00005e010, 0x113d2e0, 0xc0000a2028, 0x113d300, 0xc0000a2008)
	/home/runner/work/kubecolor/kubecolor/printer/kubectl_describe.go:85 +0xe75
github.com/dty1er/kubecolor/printer.(*KubectlOutputColoredPrinter).Print(0xc000082340, 0x113d2e0, 0xc0000a2028, 0x113d300, 0xc0000a2008)
	/home/runner/work/kubecolor/kubecolor/printer/kubectl_output_colored_printer.go:101 +0x15e
github.com/dty1er/kubecolor/command.Run.func1(0xc00009a0a0, 0x113d820, 0xc0000a2028, 0xc0000a8040)
	/home/runner/work/kubecolor/kubecolor/command/runner.go:85 +0x9b
created by github.com/dty1er/kubecolor/command.Run
	/home/runner/work/kubecolor/kubecolor/command/runner.go:84 +0x34c
![image](https://user-images.githubusercontent.com/32134057/100941703-0cee9d00-34c8-11eb-8535-f2ffb19170c6.png)

**Comment by jclynny** [comment] 2020-12-21 15:15
@dty1er Any ideas on this one?

**Comment by dty1er** [comment] 2020-12-27 04:31
Sorry to be late.
Probably this is kubecolor's bug. Let me check deeply.

**Comment by dty1er** [comment] 2020-12-27 04:51
@jclynny 

Hi, can you show me the actual output of `kubectl describe namespace` if possible?
Just showing `Resource Quotas` part is OK.

**Comment by jclynny** [comment] 2021-01-04 12:53
Sure.

`Resource Quotas
 Name:                                                                     aggregate-cap
 Resource                                                                  Used  Hard
 --------                                                                  ---   ---
 cold-hdd.storageclass.storage.k8s.io/requests.storage                     0     9600Gi
 count/configmaps                                                          4     200
 count/jobs.batch                                                          0     200
 count/persistentvolumeclaims                                              0     200
 count/pods                                                                0     200
 count/replicationcontrollers                                              0     200
 count/secrets                                                             3     200
 count/services                                                            2     200
 general-purpose-ssd.storageclass.storage.k8s.io/requests.storage          0     9600Gi
 high-provisioned-iops-ssd.storageclass.storage.k8s.io/requests.storage    0     0
 limits.cpu                                                                0     575
 limits.memory                                                             0     3000Gi
 low-provisioned-iops-ssd.storageclass.storage.k8s.io/requests.storage     0     100Gi
 medium-provisioned-iops-ssd.storageclass.storage.k8s.io/requests.storage  0     0
 requests.cpu                                                              0     575
 requests.memory                                                           0     3000Gi
 requests.storage                                                          0     9600Gi
 services.loadbalancers                                                    0     50
 services.nodeports                                                        0     50
 throughput-optimized-hdd.storageclass.storage.k8s.io/requests.storage     0     9600Gi`

**Comment by dty1er** [comment] 2021-01-04 15:26
Thank you! checking again...

**Comment by jclynny** [comment] 2021-01-11 13:40
Hi @dty1er, any updates?  Do you need more information from me?

**Comment by dty1er** [comment] 2021-01-12 02:49
@jclynny 
Sorry to be late. I found the root cause and trying to fix it.
Please wait for a bit more...

**Comment by dty1er** [comment] 2021-01-12 04:18
BTW I made a PR to fix the root cause on kubectl side. https://github.com/kubernetes/kubernetes/pull/97946
Now I'm working on a workaround fix on kubecolor side

**Comment by dty1er** [comment] 2021-01-15 04:06
Hi @jclynny , I need your help.
I applied the workaround for this issue and released the latest kubecolor v0.0.9.
Can you try it and make sure the issue is fixed now?

You can update kubecolor by `brew upgrade` if you installed `kubecolor` by homebrew. 
Or you can install the latest by go get command `go get -u github.com/dty1er/kubecolor/cmd/kubecolor`.

**Comment by jclynny** [comment] 2021-01-15 14:09
Certainly.  I will test and get back with you.  Thanks.

**Comment by jclynny** [comment] 2021-01-15 14:17
@dty1er Seems to work perfectly now.  Thanks for fixing this so quickly!

**Comment by dty1er** [comment] 2021-01-17 04:40
@jclynny 
Great to hear that!
So let me close this issue now. Sorry for the delay of my response.

Thank you for using kubecolor! If you find anything else, please submit issues.

**Closed by dty1er** 2021-01-17 04:40 UTC
