### ISSUE TITLE
Getting Vim: Warning: Output is not to a terminal while doing kubectl edit secrets ...

### ISSUE THREAD

**Issue by laurentiuspurba** [dty1er/kubecolor#18] opened 2020-10-16 18:44 UTC
I have an `alias kubectl=kubecolor` and when executed `kubectl edit secret THE_SECRET` and got the following error:
```
Vim: Warning: Output is not to a terminal
```
and my terminal just frozen.

I had to `Ctrl+C` and then exit the terminal in order to get my cursor in my terminal.

**Comment by Code-Hex** [comment] 2020-10-17 01:48
@laurentiuspurba I couldn't reproduce it in my environment.
I use the latest (v0.0.2) kubecolor. What's your version (It's better to write vim too)?

**Comment by dty1er** [comment] 2020-10-17 07:15
Currently this problem is fixed so can you update kubecolor (`go get -u github.com/dty1er/kubecolor/cmd/kubecolor`) then try again?
If it still doesn't work, please let us know shell and vim information (bash/zsh/fish, version)

**Comment by dty1er** [comment] 2020-10-23 09:09
Let me close this issue but feel free to open again if you have any issues!

**Closed by dty1er** 2020-10-23 09:09 UTC
